services:
  db:
    image: postgres:15
    restart: always
    container_name: dev_postgres_plnnr
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5555:5432"
    volumes:
      - dev_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:1.26
    container_name: temporal_plnnr
    environment:
      DB: postgres12
      POSTGRES_SEEDS: db
      POSTGRES_USER: devuser
      POSTGRES_PWD: devpassword
      DB_PORT: 5432
      DBNAME: temporal
    ports:
      - "7234:7233"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - temporal_data:/var/lib/temporal/data

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal_ui_plnnr
    ports:
      - "8090:8080"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal

volumes:
  dev_pg_data:
  temporal_data:
